apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: database
spec:
  storageClassName: {{ .Values.database.volume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi